services:
  client:
    build: ./frontend
    container_name: frontend
    env_file:
      - ./.env
    volumes:
      - ./frontend:/app
    ports:
      - 8080:80     # <-- Change the http port here
      - 8443:443    # <-- Change the https port here
    restart: on-failure

  web:
    build: Pong
    container_name: django_app
#    command: gunicorn configFiles.wsgi:application --bind 0.0.0.0:8000 --reload
    command: python manage.py runserver 0.0.0.0:8000          # <-- Add this line for hot reload
    expose:
      - 8000
    volumes:
      - static_volume:/home/Pong/web/staticfiles
      - media_volume:/home/Pong/web/mediafiles
      - ./Pong/:/home/Pong/web/
    env_file:
      - ./.env
    depends_on:
      - db
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]

  db:
    container_name: postgreSQL
    build: ./postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: on-failure

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/home/Pong/web/staticfiles
      - media_volume:/home/Pong/web/mediafiles
    ports:
      - 8080:80     # <-- Change the http port here
      - 8443:443    # <-- Change the https port here
    depends_on:
      web:
        condition: service_healthy
    restart: on-failure

volumes:
  postgres_data:
  static_volume:
  media_volume: