version: '3.8'

services:
  web:
    build: ./app
    # command: gunicorn microUserStats.wsgi --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    # expose:
    #   - 8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
  
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
     -  ./.env

  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - web

volumes:
    postgres_data:
      # driver: local
      # driver_opts:
      #   type: 'none'
      #   o: 'bind'
      #   device: "/home/rrebois/data/postgresql/data"