services:
  web:
    build: ./stats
    container_name: django_app
    command: gunicorn microUserStats.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/stats/web/staticfiles
      - ./stats/:/usr/src/stats/
    env_file:
      - ./.env
    depends_on:
      - db
    restart: on-failure
  
  db:
    container_name: postgreSQL
    build: ./postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - "5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    restart: on-failure

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - static_volume:/home/stats/web/staticfiles
    ports:
      - 8080:80     # <-- Change the http port here
      - 8443:443    # <-- Change the https port here
    depends_on:
      - web
    restart: on-failure

volumes:
  postgres_data:
  static_volume: