# Generated by Django 5.0.4 on 2024-06-24 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.JSONField(default=dict)),
                ('is_pong', models.BooleanField(default=True)),
                ('timeMatch', models.DateTimeField(auto_now_add=True)),
                ('players', models.ManyToManyField(default=list, related_name='players', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timeMatch'],
            },
        ),
    ]
