# Generated by Django 5.0.4 on 2024-06-17 13:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0, 0], size=None),
        ),
    ]
