# Generated by Django 5.0.4 on 2024-06-24 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='players',
        ),
    ]
