# Generated by Django 5.0.4 on 2024-08-28 15:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='winner',
            field=models.ManyToManyField(blank=True, default=list, related_name='winners', to=settings.AUTH_USER_MODEL),
        ),
    ]
