# Generated by Django 5.0.4 on 2024-09-18 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchs', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='tournament',
        ),
        migrations.RemoveField(
            model_name='tournamentmatch',
            name='match',
        ),
        migrations.DeleteModel(
            name='Tournament',
        ),
        migrations.DeleteModel(
            name='TournamentMatch',
        ),
    ]
