# Generated by Django 5.0.4 on 2024-04-18 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_wins', models.IntegerField(default=0)),
                ('user_losses', models.IntegerField(default=0)),
                ('user_elo', models.IntegerField(default=900)),
            ],
        ),
    ]
