# Generated by Django 5.0.4 on 2024-05-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userStats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default_pp.jpg', upload_to='./static/images/profile_pics/'),
        ),
    ]
