# Generated by Django 5.0.4 on 2024-05-27 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userStats', '0005_alter_user_friends_alter_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default_pp.jpg', upload_to='./media/profile_pics/'),
        ),
    ]
