# Generated by Django 5.0.4 on 2024-06-23 10:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_losses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default={0}, size=None),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_winrate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default={0}, size=None),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_wins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default={0}, size=None),
        ),
    ]
