# Generated by Django 5.0.4 on 2024-07-30 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatars',
            name='image',
            field=models.ImageField(max_length=255, upload_to='profile_pics/'),
        ),
    ]
