# Generated by Django 5.0.4 on 2024-07-30 15:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_alter_avatars_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatars',
            name='uploaded_from',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
