# Generated by Django 5.0.4 on 2024-06-23 10:58

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_alter_userdata_user_losses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_losses',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0, 0], size=None),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_winrate',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=[0, 0], size=None),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_wins',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0, 0], size=None),
        ),
    ]
