# Generated by Django 5.0.4 on 2024-07-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0002_remove_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('English', 'en'), ('French', 'fr'), ('Spanish', 'es'), ('Portuguese', 'pt')], default='English'),
        ),
    ]
