# Generated by Django 5.0.4 on 2024-07-09 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0003_alter_userdata_user_losses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='languages',
            field=models.CharField(default='en'),
        ),
    ]
