# Generated by Django 5.0.4 on 2024-07-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0004_user_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='languages',
            field=models.CharField(default='English'),
        ),
    ]
