# Generated by Django 5.0.4 on 2024-07-09 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManagement', '0005_alter_user_languages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='languages',
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('English', 'en'), ('French', 'fr'), ('Spanish', 'es')], default='English'),
        ),
    ]
